name: "Book store"
services:  
  postgresql:
    image: "postgres:15"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=BookCatalogGraphql"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=P@55w0rd"
